import { Share } from 'react-native';

// This version builds a clean, readable text report and uses React Native's
// BUILT-IN Share API - no extra native libraries, no linking issues, works
// reliably out of the box on every device.
//
// The user's share sheet will let them save it as a note, email it, send it
// via WhatsApp, etc. If you specifically need a real .pdf file later (once
// you have more time to debug native library linking), we can revisit
// react-native-html-to-pdf or try react-native-print instead.

export async function generateAndShareReport({ profile, readingHistory, moodLog }) {
  const dateStr = new Date().toLocaleString();

  const readingLines = readingHistory
    .slice(0, 50) // keep the shared text reasonably short
    .map(
      (r) =>
        `${r.time} | HR: ${r.heartRate ?? '--'} BPM | Kicks: ${r.kickCount} | Movement: ${r.movement}`
    )
    .join('\n');

  const moodLines = moodLog
    .slice(0, 30)
    .map((m) => `${m.timestamp} | ${m.emoji} ${m.label}`)
    .join('\n');

  const reportText =
    `FETAL CARE AI - HEALTH REPORT\n` +
    `================================\n` +
    `Name: ${profile?.name ?? '-'}\n` +
    `Generated: ${dateStr}\n` +
    `Emergency Contact: ${profile?.emergencyContact ?? '-'}\n\n` +
    `VITALS & MOVEMENT HISTORY (most recent ${Math.min(readingHistory.length, 50)} entries)\n` +
    `--------------------------------\n` +
    (readingLines || 'No readings recorded yet.\n') +
    `\n\nMOOD LOG (most recent ${Math.min(moodLog.length, 30)} entries)\n` +
    `--------------------------------\n` +
    (moodLines || 'No mood entries recorded yet.\n') +
    `\n\nNote: This report is generated by a wearable monitoring prototype and is ` +
    `not a substitute for professional medical diagnosis. Please consult a doctor ` +
    `for any health concerns.`;

  try {
    const result = await Share.share({
      title: 'Fetal Care AI - Health Report',
      message: reportText,
    });
    console.log('Share result:', result);
    return result;
  } catch (err) {
    console.log('Share failed:', err);
    throw new Error('Could not open share sheet: ' + err.message);
  }
}
